### ISSUE TITLE
how do i take user input as string. as i write: name = input("enter a name:")

### ISSUE THREAD

**Issue by madhurmj21** [CodeKul/Python-Jan-2019-Weekday-4pm-5pm#1]
how do i take user input as string.
as i write:
name = input("enter a name:")
and when i give my name in input it give me error as : 
Traceback (most recent call last):
  File "inputname.py", line 1, in <module>
    name =  input("enter a name:")
  File "<string>", line 1, in <module>
NameError: name 'madhur' is not defined

**Comment by varunkudalkar** [comment]
**input** function lets you ask a user for some **text input**.
You call this function to tell the program to stop and wait for the user to key in the data.
In **Python 2**, you have a built-in function **raw_input()**, whereas in **Python 3**, you have **input()**.
The program will resume once the user presses the ENTER or RETURN key.

The string is the default of input. There are two options below to change it.

```
sample = input("Sample")
sample = int(sample)
```
